'use client';

import React from 'react';
import { Card, CardHeader } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { Sparkles, Terminal, ShieldAlert, Cpu, CheckCircle, Database } from 'lucide-react';
import { DEMO_DATA_NOTICE } from '@/data/demo';

export default function InsightsPage() {
  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-3 pb-2 border-b border-command-border/60">
        <div>
          <h2 className="text-xl font-bold tracking-tight text-white flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-purple-400" />
            AI Intelligence & Municipal Analytics
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Meta Llama 3.2 3B Natural Language Understanding & Strategic Operational Synthesis.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Badge variant="purple" className="font-mono">
            Ollama: Llama 3.2 3B
          </Badge>
        </div>
      </div>

      {/* Simulated Demonstration Warning Card */}
      <div className="p-4 rounded-xl bg-amber-950/40 border border-amber-500/40 flex items-start gap-3 text-xs">
        <ShieldAlert className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
        <div>
          <h4 className="font-bold text-amber-300 uppercase font-mono">{DEMO_DATA_NOTICE}</h4>
          <p className="text-slate-300 mt-0.5 leading-relaxed">
            All analytical summaries and hotspot metrics in this interface are generated from synthetic Bengaluru urban demonstration sets. They are structured to validate the 6-stage SwachhRoute AI pipeline for HackForge 2026.
          </p>
        </div>
      </div>

      {/* Architecture Separation of Concerns Card */}
      <Card glow="cyan">
        <CardHeader
          title="Strict Separation of Concerns Architecture"
          subtitle="Rule: Llama 3.2 3B handles ONLY Natural Language Understanding"
          icon={Cpu}
        />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-xs">
          {/* What Llama Handles */}
          <div className="p-4 rounded-lg bg-emerald-950/20 border border-emerald-500/30 space-y-2">
            <h4 className="font-bold text-emerald-300 uppercase font-mono flex items-center gap-2">
              <CheckCircle className="w-4 h-4 text-emerald-400" />
              Llama 3.2 3B Responsibilities (Permitted)
            </h4>
            <ul className="space-y-1.5 text-slate-300 list-disc list-inside">
              <li>Citizen complaint language parsing & intent extraction</li>
              <li>Hazard interpretation (biohazard, chemical, flammable)</li>
              <li>Severity classification (low, medium, high, critical)</li>
              <li>Required machinery recommendation (Compactor, JCB, Mini Tipper)</li>
              <li>Driver shift briefing synthesis</li>
              <li>Municipal executive summaries</li>
            </ul>
          </div>

          {/* What Llama MUST NOT Handle */}
          <div className="p-4 rounded-lg bg-rose-950/20 border border-rose-500/30 space-y-2">
            <h4 className="font-bold text-rose-300 uppercase font-mono flex items-center gap-2">
              <ShieldAlert className="w-4 h-4 text-rose-400" />
              Deterministic Engines Only (Forbidden for LLM)
            </h4>
            <ul className="space-y-1.5 text-slate-300 list-disc list-inside">
              <li>EPSG:4326 to EPSG:3857 coordinate projection</li>
              <li>Geographic distance & Haversine / Euclidean calculations</li>
              <li>DBSCAN hotspot density clustering (Scikit-learn)</li>
              <li>Convex hull polygon calculations (SciPy)</li>
              <li>CVRP route optimization & fleet assignment (Google OR-Tools)</li>
              <li>Road snapping & turn geometry (OSRM)</li>
            </ul>
          </div>
        </div>
      </Card>

      {/* Mock AI Executive Synthesis Card */}
      <Card glow="purple">
        <CardHeader
          title="Executive Operational Briefing (Synthesized)"
          subtitle="Generated by Meta Llama 3.2 3B Engine"
          icon={Terminal}
        />
        <div className="p-4 rounded-lg bg-command-surface/80 border border-command-border text-xs text-slate-300 space-y-3 font-sans leading-relaxed">
          <p>
            <strong>Operational Status:</strong> Sector telemetry indicates 3 active high-density waste clusters totaling 5.2 metric tons across Indiranagar, Koramangala, and Whitefield corridors.
          </p>
          <p>
            <strong>Machinery Directives:</strong> Indiranagar (Cluster #1) requires heavy loader (JCB) and Ro-Ro deployment to clear concrete and construction debris obstruction. Koramangala (Cluster #2) has critical drain contamination requiring suction tanker operation.
          </p>
          <p>
            <strong>Fleet Recommendation:</strong> Deploy 2 available heavy compactors from Central Municipal Depot immediately to prevent weekend overflow.
          </p>
        </div>
      </Card>
    </div>
  );
}
